import ExcelJS from "exceljs";
import { formatSriLankaDateTime, getSriLankaNowFormatted } from "./timeUtils";
import { normalizePaymentType, getCategories } from "../services/firebase/categoryService";

/**
 * Generate a pure Transaction Report Workbook in ExcelJS
 * - Auto-resolves payment plan strictly based on Master Category Configuration
 * - NO Allocation ID column
 * - Presents Employee Category & Auto Payment Plan (Full Paid, Half Paid, Not Paid)
 * - Excludes removed Section/Department fields
 * - Columns formatted in Sri Jayawardenepura Time (Asia/Colombo / UTC+05:30)
 * - Auto-filters enabled on table headers for easy sorting and filtering in Excel
 */
export async function buildMealReportWorkbook({
  allocations = [],
  title = "MEAL MANAGEMENT SYSTEM - ALLOCATIONS TRANSACTION REPORT",
  dateRangeStr = "All Records",
  generatedBy = "System Administrator",
  categoryMap = null
}) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Hayleys Meal Management System";
  workbook.created = new Date();

  // Load master categories if not passed
  let catMap = categoryMap;
  if (!catMap) {
    try {
      const cats = await getCategories();
      catMap = {};
      cats.forEach((c) => {
        if (c.category_name) {
          catMap[c.category_name.toLowerCase()] = c.configuration_detail;
        }
      });
    } catch (e) {
      catMap = {};
    }
  }

  // Single dedicated worksheet for transaction entries
  const worksheet = workbook.addWorksheet("Meal Transactions", {
    views: [{ showGridLines: true, state: "frozen", ySplit: 3 }] // Freeze top 3 rows for easy scrolling
  });

  // ----------------------------------------------------
  // 1. Report Title & Header Banner
  // ----------------------------------------------------
  worksheet.mergeCells("A1:J1");
  const titleCell = worksheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { name: "Calibri", size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF064E3B" } };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };
  worksheet.getRow(1).height = 34;

  // 2. Subtitle / Metadata Row
  worksheet.mergeCells("A2:J2");
  const subCell = worksheet.getCell("A2");
  const sriLankaNow = getSriLankaNowFormatted();
  subCell.value = `Period: ${dateRangeStr}  |  Generated on: ${sriLankaNow} (Sri Jayawardenepura Time)  |  Generated by: ${generatedBy}  |  Total Records: ${allocations.length}`;
  subCell.font = { name: "Calibri", size: 10, italic: true, color: { argb: "FFFFFFFF" } };
  subCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF047857" } };
  subCell.alignment = { horizontal: "center", vertical: "middle" };
  worksheet.getRow(2).height = 24;

  // ----------------------------------------------------
  // 3. Table Column Headers (Row 3 - NO Allocation ID, NO Section/Dept)
  // ----------------------------------------------------
  const headers = [
    "Allocation Date",
    "Employee ID",
    "Full Name",
    "Company",
    "Meal Category",
    "Payment Plan",
    "Meal Slot",
    "Status",
    "Created At (Sri Lanka Time)",
    "Dispensed At (Sri Lanka Time)"
  ];

  const headerRow = worksheet.addRow(headers);
  headerRow.height = 28;
  headerRow.font = { name: "Calibri", size: 11, bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.alignment = { horizontal: "center", vertical: "middle", wrapText: true };

  // Style header cells
  for (let c = 1; c <= headers.length; c++) {
    const cell = headerRow.getCell(c);
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF059669" } };
    cell.border = {
      top: { style: "thin", color: { argb: "FF064E3B" } },
      left: { style: "thin", color: { argb: "FF064E3B" } },
      bottom: { style: "medium", color: { argb: "FF064E3B" } },
      right: { style: "thin", color: { argb: "FF064E3B" } }
    };
  }

  // ----------------------------------------------------
  // 4. Data Rows
  // ----------------------------------------------------
  allocations.forEach((item, index) => {
    const createdAtFormatted = formatSriLankaDateTime(item.created_at);
    const receivedAtFormatted = formatSriLankaDateTime(item.received_at);

    const isRecv =
      (item.status || "").toLowerCase() === "recieved" ||
      (item.status || "").toLowerCase() === "received";

    const categoryName = item.category_name || item.category_employment || item.employee_category || "Staff";
    
    // Auto-resolve subsidy from Master Category definition
    const masterSubsidy = catMap[categoryName.toLowerCase()] || item.pay_category || item.configuration_detail;
    const normalizedPayment = normalizePaymentType(masterSubsidy);

    const row = worksheet.addRow([
      item.date || "-",
      item.employee_id || item.emp_id || "-",
      item.employee_name || item.name || "-",
      item.company || "Hayleys Eco Solutions",
      categoryName,
      normalizedPayment,
      item.meal_type || "-",
      isRecv ? "Received" : "Ordered",
      createdAtFormatted,
      receivedAtFormatted
    ]);

    row.height = 22;
    row.font = { name: "Calibri", size: 10 };
    row.alignment = { vertical: "middle" };

    // Zebra striping
    const isEven = index % 2 === 1;
    const bgFill = isEven
      ? { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } }
      : { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFFFFF" } };

    for (let c = 1; c <= headers.length; c++) {
      const cell = row.getCell(c);
      cell.fill = bgFill;
      cell.border = {
        top: { style: "hair", color: { argb: "FFE2E8F0" } },
        left: { style: "hair", color: { argb: "FFE2E8F0" } },
        bottom: { style: "hair", color: { argb: "FFE2E8F0" } },
        right: { style: "hair", color: { argb: "FFE2E8F0" } }
      };
    }

    // Align specific columns
    row.getCell(1).alignment = { horizontal: "center", vertical: "middle" }; // Date
    row.getCell(2).alignment = { horizontal: "center", vertical: "middle" }; // Emp ID
    row.getCell(5).alignment = { horizontal: "center", vertical: "middle" }; // Category
    row.getCell(6).alignment = { horizontal: "center", vertical: "middle" }; // Subsidy
    row.getCell(7).alignment = { horizontal: "center", vertical: "middle" }; // Meal Slot
    row.getCell(8).alignment = { horizontal: "center", vertical: "middle" }; // Status
    row.getCell(9).alignment = { horizontal: "center", vertical: "middle" }; // Created At
    row.getCell(10).alignment = { horizontal: "center", vertical: "middle" }; // Dispensed At

    // Style payment subsidy
    const payCell = row.getCell(6);
    if (normalizedPayment === "Full Paid") {
      payCell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF047857" } };
    } else if (normalizedPayment === "Half Paid") {
      payCell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FFD97706" } };
    } else {
      payCell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FFDC2626" } };
    }

    // Style status
    const statusCell = row.getCell(8);
    if (isRecv) {
      statusCell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF047857" } };
    } else {
      statusCell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF2563EB" } };
    }
  });

  // Enable Auto-Filter on header row
  worksheet.autoFilter = `A3:J${Math.max(3, allocations.length + 3)}`;

  // Set explicit, readable column widths
  worksheet.getColumn(1).width = 16;  // Allocation Date
  worksheet.getColumn(2).width = 16;  // Employee ID
  worksheet.getColumn(3).width = 26;  // Full Name
  worksheet.getColumn(4).width = 28;  // Company
  worksheet.getColumn(5).width = 18;  // Meal Category
  worksheet.getColumn(6).width = 20;  // Payment Plan
  worksheet.getColumn(7).width = 14;  // Meal Slot
  worksheet.getColumn(8).width = 14;  // Status
  worksheet.getColumn(9).width = 26;  // Created At (Sri Lanka Time)
  worksheet.getColumn(10).width = 26; // Dispensed At (Sri Lanka Time)

  return workbook;
}

/**
 * Generate and trigger download of the report in browser
 */
export async function generateTransactionEntriesReport({
  allocations = [],
  title = "MEAL MANAGEMENT SYSTEM - ALLOCATIONS TRANSACTION REPORT",
  dateRangeStr = "All Records",
  generatedBy = "System Administrator",
  customFilename = null
}) {
  const workbook = await buildMealReportWorkbook({ allocations, title, dateRangeStr, generatedBy });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  });

  const cleanDate = new Date().toISOString().split("T")[0];
  const filename = customFilename || `Meal_Allocations_Transactions_${cleanDate}.xlsx`;

  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);

  return { success: true, filename, buffer };
}

/**
 * Legacy alias for backwards compatibility
 */
export async function generateFormattedMealReport(params) {
  return generateTransactionEntriesReport(params);
}
