import ExcelJS from "exceljs";
import { formatSriLankaDateTime, getSriLankaNowFormatted } from "./timeUtils";

/**
 * Generate a pure Transaction Report of Entries in Excel
 * - Direct, clean list of every allocation entry / transaction
 * - No redundant summary sheets
 * - Columns formatted in Sri Jayawardenepura Time (Asia/Colombo / UTC+05:30)
 * - Auto-filters enabled on table headers for easy sorting and filtering in Excel
 */
export async function generateTransactionEntriesReport({
  allocations = [],
  title = "MEAL MANAGEMENT PROJECT - MEAL ALLOCATIONS TRANSACTION REPORT",
  dateRangeStr = "All Records",
  generatedBy = "System Administrator"
}) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Meal Management Project";
  workbook.created = new Date();

  // Single dedicated worksheet for transaction entries
  const worksheet = workbook.addWorksheet("Meal Transactions", {
    views: [{ showGridLines: true, state: "frozen", ySplit: 3 }] // Freeze top 3 rows for easy scrolling
  });

  // ----------------------------------------------------
  // 1. Report Title & Header Banner
  // ----------------------------------------------------
  worksheet.mergeCells("A1:L1");
  const titleCell = worksheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { name: "Calibri", size: 15, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF064E3B" } };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };
  worksheet.getRow(1).height = 36;

  // 2. Subtitle / Metadata Row
  worksheet.mergeCells("A2:L2");
  const subCell = worksheet.getCell("A2");
  const sriLankaNow = getSriLankaNowFormatted();
  subCell.value = `Period: ${dateRangeStr}  |  Generated on: ${sriLankaNow} (Sri Jayawardenepura Time)  |  Generated by: ${generatedBy}  |  Total Entries: ${allocations.length}`;
  subCell.font = { name: "Calibri", size: 10, italic: true, color: { argb: "FFFFFFFF" } };
  subCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF047857" } };
  subCell.alignment = { horizontal: "center", vertical: "middle" };
  worksheet.getRow(2).height = 24;

  // ----------------------------------------------------
  // 3. Table Column Headers (Row 3)
  // ----------------------------------------------------
  const headers = [
    "Allocation ID",
    "Allocation Date",
    "Employee ID",
    "Employee Name",
    "Company / Plant",
    "Section / Department",
    "Meal Slot",
    "Subsidy Plan",
    "Status",
    "Created By",
    "Created At (Sri Lanka Time)",
    "Dispensed At (Sri Lanka Time)"
  ];

  const headerRow = worksheet.addRow(headers);
  headerRow.height = 28;
  headerRow.font = { name: "Calibri", size: 11, bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.alignment = { horizontal: "center", vertical: "middle", wrapText: true };

  // Style header cells
  for (let c = 1; c <= headers.length; c++) {
    const cell = headerRow.getCell(c);
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF059669" } };
    cell.border = {
      top: { style: "thin", color: { argb: "FF064E3B" } },
      left: { style: "thin", color: { argb: "FF064E3B" } },
      bottom: { style: "medium", color: { argb: "FF064E3B" } },
      right: { style: "thin", color: { argb: "FF064E3B" } }
    };
  }

  // ----------------------------------------------------
  // 4. Data Rows
  // ----------------------------------------------------
  allocations.forEach((item, index) => {
    const createdAtFormatted = formatSriLankaDateTime(item.created_at);
    const receivedAtFormatted = formatSriLankaDateTime(item.received_at);

    const isRecv =
      (item.status || "").toLowerCase() === "recieved" ||
      (item.status || "").toLowerCase() === "received";

    const row = worksheet.addRow([
      item.id || "-",
      item.date || "-",
      item.employee_id || "-",
      item.employee_name || "-",
      item.company || "Meal Management Project",
      item.section || "-",
      item.meal_type || "-",
      item.pay_category || "Free Meal",
      isRecv ? "Received" : "Ordered",
      item.created_by || "-",
      createdAtFormatted,
      receivedAtFormatted
    ]);

    row.height = 22;
    row.font = { name: "Calibri", size: 10 };
    row.alignment = { vertical: "middle" };

    // Zebra striping
    const isEven = index % 2 === 1;
    const bgFill = isEven
      ? { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } }
      : { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFFFFF" } };

    for (let c = 1; c <= headers.length; c++) {
      const cell = row.getCell(c);
      cell.fill = bgFill;
      cell.border = {
        top: { style: "hair", color: { argb: "FFE2E8F0" } },
        left: { style: "hair", color: { argb: "FFE2E8F0" } },
        bottom: { style: "hair", color: { argb: "FFE2E8F0" } },
        right: { style: "hair", color: { argb: "FFE2E8F0" } }
      };
    }

    // Align specific columns
    row.getCell(1).alignment = { horizontal: "center", vertical: "middle" }; // ID
    row.getCell(2).alignment = { horizontal: "center", vertical: "middle" }; // Date
    row.getCell(3).alignment = { horizontal: "center", vertical: "middle" }; // Emp ID
    row.getCell(7).alignment = { horizontal: "center", vertical: "middle" }; // Meal Slot
    row.getCell(8).alignment = { horizontal: "center", vertical: "middle" }; // Subsidy
    row.getCell(9).alignment = { horizontal: "center", vertical: "middle" }; // Status
    row.getCell(11).alignment = { horizontal: "center", vertical: "middle" }; // Created At
    row.getCell(12).alignment = { horizontal: "center", vertical: "middle" }; // Dispensed At

    // Highlight Status
    const statusCell = row.getCell(9);
    if (isRecv) {
      statusCell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF047857" } };
    } else {
      statusCell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF2563EB" } };
    }
  });

  // Enable Auto-Filter on header row
  worksheet.autoFilter = `A3:L${Math.max(3, allocations.length + 3)}`;

  // Set explicit, readable column widths
  worksheet.getColumn(1).width = 24;  // Allocation ID
  worksheet.getColumn(2).width = 15;  // Allocation Date
  worksheet.getColumn(3).width = 15;  // Employee ID
  worksheet.getColumn(4).width = 26;  // Employee Name
  worksheet.getColumn(5).width = 24;  // Company
  worksheet.getColumn(6).width = 24;  // Section / Dept
  worksheet.getColumn(7).width = 14;  // Meal Slot
  worksheet.getColumn(8).width = 18;  // Subsidy Plan
  worksheet.getColumn(9).width = 14;  // Status
  worksheet.getColumn(10).width = 20; // Created By
  worksheet.getColumn(11).width = 26; // Created At (Sri Lanka Time)
  worksheet.getColumn(12).width = 26; // Dispensed At (Sri Lanka Time)

  // ----------------------------------------------------
  // 5. Export as Buffer & Trigger Browser Download
  // ----------------------------------------------------
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  });

  const cleanDate = new Date().toISOString().split("T")[0];
  const filename = `Meal_Allocations_Transactions_${cleanDate}.xlsx`;

  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);

  return { success: true, filename };
}

/**
 * Legacy alias for backwards compatibility
 */
export async function generateFormattedMealReport(params) {
  return generateTransactionEntriesReport(params);
}
