import ExcelJS from "exceljs";
import { formatSriLankaDateTime, getSriLankaNowFormatted } from "./timeUtils";

/**
 * Generate a beautifully formatted Excel workbook with summary cards and multi-sheet analytics
 * All dates & timestamps are strictly formatted in Sri Jayawardenepura Time (Asia/Colombo / UTC+05:30)
 */
export async function generateFormattedMealReport({
  allocations = [],
  title = "MEAL MANAGEMENT PROJECT - ALLOCATIONS & CONSUMPTION REPORT",
  dateRangeStr = "All Time",
  generatedBy = "System Administrator"
}) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Meal Management Project";
  workbook.created = new Date();

  // ----------------------------------------------------
  // Calculate Aggregations
  // ----------------------------------------------------
  const totalMeals = allocations.length;
  const breakfastCount = allocations.filter(a => a.meal_type === "Breakfast").length;
  const lunchCount = allocations.filter(a => a.meal_type === "Lunch").length;
  const dinnerCount = allocations.filter(a => a.meal_type === "Dinner").length;

  const receivedCount = allocations.filter(a => (a.status || "").toLowerCase() === "recieved" || (a.status || "").toLowerCase() === "received").length;
  const pendingCount = totalMeals - receivedCount;

  const freeCount = allocations.filter(a => (a.pay_category || "").toLowerCase().includes("free")).length;
  const halfPaidCount = allocations.filter(a => (a.pay_category || "").toLowerCase().includes("half")).length;
  const notPaidCount = allocations.filter(a => (a.pay_category || "").toLowerCase().includes("not")).length;

  // Department Aggregation
  const deptMap = {};
  allocations.forEach(a => {
    const d = a.section || "General Operations";
    if (!deptMap[d]) {
      deptMap[d] = { total: 0, breakfast: 0, lunch: 0, dinner: 0, received: 0 };
    }
    deptMap[d].total += 1;
    if (a.meal_type === "Breakfast") deptMap[d].breakfast += 1;
    if (a.meal_type === "Lunch") deptMap[d].lunch += 1;
    if (a.meal_type === "Dinner") deptMap[d].dinner += 1;
    if ((a.status || "").toLowerCase() === "recieved" || (a.status || "").toLowerCase() === "received") deptMap[d].received += 1;
  });

  // ----------------------------------------------------
  // SHEET 1: Executive Summary & Department Breakdown
  // ----------------------------------------------------
  const summarySheet = workbook.addWorksheet("Executive Summary", {
    views: [{ showGridLines: true }]
  });

  // Title Header
  summarySheet.mergeCells("A1:F1");
  const titleCell = summarySheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { name: "Arial", size: 15, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF064E3B" } };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };
  summarySheet.getRow(1).height = 36;

  // Subheader with Sri Jayawardenepura Time
  summarySheet.mergeCells("A2:F2");
  const subCell = summarySheet.getCell("A2");
  const sriLankaNow = getSriLankaNowFormatted();
  subCell.value = `Report Period: ${dateRangeStr}  |  Generated on: ${sriLankaNow} (Sri Jayawardenepura Time)  |  Generated by: ${generatedBy}`;
  subCell.font = { name: "Arial", size: 10, italic: true, color: { argb: "FFFFFFFF" } };
  subCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF047857" } };
  subCell.alignment = { horizontal: "center", vertical: "middle" };
  summarySheet.getRow(2).height = 24;

  summarySheet.addRow([]); // Blank row

  // Key KPI Cards Table
  summarySheet.addRow(["KEY PERFORMANCE METRICS", "", "", "", "", ""]);
  summarySheet.mergeCells("A4:F4");
  const kpiHeader = summarySheet.getCell("A4");
  kpiHeader.font = { name: "Arial", size: 12, bold: true, color: { argb: "FF064E3B" } };
  kpiHeader.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD1FAE5" } };

  const kpiRows = [
    ["Total Meals Scheduled", totalMeals, "Breakfast Portions", breakfastCount, "Free Meal Subsidies", freeCount],
    ["Total Meals Dispensed", receivedCount, "Lunch Portions", lunchCount, "Half-Paid Subsidies", halfPaidCount],
    ["Pending Dispensing", pendingCount, "Dinner Portions", dinnerCount, "Not Paid / Standard", notPaidCount]
  ];

  kpiRows.forEach(r => {
    const row = summarySheet.addRow(r);
    row.font = { name: "Arial", size: 11 };
    row.alignment = { vertical: "middle" };
    // Style key numeric columns
    [2, 4, 6].forEach(colIdx => {
      const cell = row.getCell(colIdx);
      cell.font = { bold: true };
      cell.alignment = { horizontal: "right" };
    });
  });

  summarySheet.addRow([]); // Blank

  // Department Breakdown Table
  summarySheet.addRow(["DEPARTMENT CONSUMPTION BREAKDOWN", "", "", "", "", ""]);
  summarySheet.mergeCells("A9:F9");
  const deptHeader = summarySheet.getCell("A9");
  deptHeader.font = { name: "Arial", size: 12, bold: true, color: { argb: "FF064E3B" } };
  deptHeader.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD1FAE5" } };

  // Department Table Columns
  const deptColsRow = summarySheet.addRow([
    "Department / Section",
    "Total Scheduled",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Dispensed (Received)"
  ]);
  deptColsRow.font = { name: "Arial", size: 11, bold: true, color: { argb: "FFFFFFFF" } };
  deptColsRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF059669" } };
  deptColsRow.alignment = { horizontal: "center", vertical: "middle" };

  Object.entries(deptMap).forEach(([deptName, counts], idx) => {
    const dRow = summarySheet.addRow([
      deptName,
      counts.total,
      counts.breakfast,
      counts.lunch,
      counts.dinner,
      counts.received
    ]);
    dRow.font = { name: "Arial", size: 10 };
    if (idx % 2 === 1) {
      dRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } };
    }
    // Align numbers right
    for (let c = 2; c <= 6; c++) {
      dRow.getCell(c).alignment = { horizontal: "right" };
    }
  });

  // Department Totals Row
  const deptTotalRow = summarySheet.addRow([
    "TOTAL",
    totalMeals,
    breakfastCount,
    lunchCount,
    dinnerCount,
    receivedCount
  ]);
  deptTotalRow.font = { name: "Arial", size: 11, bold: true, color: { argb: "FF064E3B" } };
  deptTotalRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFECFDF5" } };
  for (let c = 2; c <= 6; c++) {
    deptTotalRow.getCell(c).alignment = { horizontal: "right" };
  }

  // Adjust column widths for Summary sheet
  summarySheet.getColumn(1).width = 34;
  summarySheet.getColumn(2).width = 20;
  summarySheet.getColumn(3).width = 20;
  summarySheet.getColumn(4).width = 20;
  summarySheet.getColumn(5).width = 20;
  summarySheet.getColumn(6).width = 24;

  // ----------------------------------------------------
  // SHEET 2: Detailed Allocation Transactions (Sri Lanka Time Formatted)
  // ----------------------------------------------------
  const detailSheet = workbook.addWorksheet("All Allocations Log", {
    views: [{ showGridLines: true }]
  });

  // Title Row
  detailSheet.mergeCells("A1:L1");
  const dTitle = detailSheet.getCell("A1");
  dTitle.value = "DETAILED MEAL ALLOCATIONS MASTER LOG (SRI JAYAWARDENEPURA TIME)";
  dTitle.font = { name: "Arial", size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  dTitle.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF064E3B" } };
  dTitle.alignment = { horizontal: "center", vertical: "middle" };
  detailSheet.getRow(1).height = 30;

  // Table Headers
  const headerRow = detailSheet.addRow([
    "Allocation ID",
    "Allocation Date",
    "Employee ID",
    "Employee Name",
    "Company / Plant",
    "Section / Department",
    "Meal Slot",
    "Subsidy Plan",
    "Status",
    "Created By",
    "Created At (Sri Lanka Time)",
    "Dispensed At (Sri Lanka Time)"
  ]);
  headerRow.font = { name: "Arial", size: 11, bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF059669" } };
  headerRow.alignment = { horizontal: "center", vertical: "middle" };
  detailSheet.getRow(2).height = 26;

  // Populate data with Sri Jayawardenepura Time formatted timestamps
  allocations.forEach((item, index) => {
    const createdAtFormatted = formatSriLankaDateTime(item.created_at);
    const receivedAtFormatted = formatSriLankaDateTime(item.received_at);

    const row = detailSheet.addRow([
      item.id || "-",
      item.date || "-",
      item.employee_id || "-",
      item.employee_name || "-",
      item.company || "Meal Management Project",
      item.section || "-",
      item.meal_type || "-",
      item.pay_category || "Free Meal",
      item.status || "Ordered",
      item.created_by || "-",
      createdAtFormatted,
      receivedAtFormatted
    ]);

    row.font = { name: "Arial", size: 10 };
    if (index % 2 === 1) {
      row.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } };
    }

    // Status formatting
    const statusCell = row.getCell(9);
    if ((item.status || "").toLowerCase() === "recieved" || (item.status || "").toLowerCase() === "received") {
      statusCell.font = { color: { argb: "FF047857" }, bold: true };
    } else {
      statusCell.font = { color: { argb: "FF2563EB" }, bold: true };
    }
  });

  // Adjust Column Widths
  detailSheet.getColumn(1).width = 26;
  detailSheet.getColumn(2).width = 16;
  detailSheet.getColumn(3).width = 16;
  detailSheet.getColumn(4).width = 26;
  detailSheet.getColumn(5).width = 24;
  detailSheet.getColumn(6).width = 26;
  detailSheet.getColumn(7).width = 14;
  detailSheet.getColumn(8).width = 18;
  detailSheet.getColumn(9).width = 14;
  detailSheet.getColumn(10).width = 20;
  detailSheet.getColumn(11).width = 26; // Created At
  detailSheet.getColumn(12).width = 26; // Received At

  // ----------------------------------------------------
  // Export as Buffer & Trigger Browser Download
  // ----------------------------------------------------
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  
  const cleanDate = new Date().toISOString().split("T")[0];
  const filename = `Meal_Management_Report_${cleanDate}.xlsx`;

  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);

  return { success: true, filename };
}
